name: chatgpt-research
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - wikipedia-api
  - pytorch
  - transformers
  - ca-certificates
  - certifi
  - openssl
  - faiss-gpu
